apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploys-jenkins
  namespace: yomisp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: intern-container-jenkins
        image: ${params.IMAGE}:1
        ports:
        - containerPort: 5000
